apiVersion: v1
kind: Service
metadata:
  name: mysql
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
  labels:
    run: mysql
spec:
  type: LoadBalancer
  selector:
    run: mysql
  ports:
  - name: sql-port
    protocol: TCP
    port: 3306
    targetPort: 3306