FROM    alpine:3.12

COPY    setup.sh /tmp/
RUN     apk update && apk add nginx openssl 
RUN     apk add --no-cache supervisor


RUN     mkdir -p /etc/nginx/ssl/ && mkdir /run/nginx
RUN     openssl req -newkey rsa:4096 -x509 -sha256 -days 365 -nodes -out /etc/nginx/ssl/localhost.pem -keyout /etc/nginx/ssl/localhost.key -subj "/C=BE/ST=Bruxelles/L=Bruxelles/O=19 School/OU=Bourdanne/CN=localhost"

COPY    nginx.conf /etc/nginx/
COPY    index.html /var/www/localhost/
#       telegraf
RUN     apk add telegraf --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
COPY    telegraf.conf /etc/telegraf.conf

RUN     mkdir -p /var/log/supervisor
COPY    ./supervisord.conf /etc/

CMD     sh tmp/setup.sh
