apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: img_influxdb
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
          name: https
        volumeMounts:
        - name: influxdb-persistent-storage
          mountPath: /root
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - -c
            - 'pgrep telegraf && pgrep influxd'
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: influxdb-persistent-storage
        persistentVolumeClaim:
          claimName: influxdb-pvc