apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
  name: ftps-service
  labels:
    app: ftps
spec:
  ports:
    - port: 21
      name: ftps
    - port: 21000
      name: ftps00
    - port: 21001
      name: ftps01
    - port: 21002
      name: ftps02
    - port: 21003
      name: ftps03
  selector:
    app: ftps
  type: LoadBalancer