apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
  labels:
    app: influxdb
spec:
  type: ClusterIP
  selector:
    app: influxdb
  ports:
  - name: https
    port: 8086
    targetPort: 8086