apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  selector:
    app: mysql
  ports:
    - name: sql-port
      protocol: TCP
      port: 3306
      targetPort: 3306
