apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
  labels:
    run: wordpress
spec:
  type: LoadBalancer
  selector:
    run: wordpress
  ports:
  - name: https
    port: 5050
    targetPort: 5050
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    run: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress
  labels:
    run: wordpress
spec:
  serviceName: wordpress
  replicas: 1
  selector:
    matchLabels:
      run: wordpress
  template:
    metadata:
      labels:
        run: wordpress
    spec:
      containers:
      - name: wordpress
        image: service_wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
          name: https