apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  type: LoadBalancer
  selector:
    run: wordpress
  ports:
  - port: 5050
    protocol: TCP
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: service_wordpress
        imagePullPolicy: Never
        env:
        - name: DB_NAME
          value: wordpress
        - name: DB_USER
          value: admin
        - name: DB_PASSWORD
          value: admin
        - name: DB_HOST
          value: mysql
        ports:
        - containerPort: 5050