apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-share-ip: minikube
  labels:
    run: ftps
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.0.2
  selector:
    run: ftps
  ports:
  - name: ftps
    port: 21
    targetPort: 21
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ftps
  labels:
    run: ftps
spec:
  serviceName: ftps
  replicas: 1
  selector:
    matchLabels:
      run: ftps
  template:
    metadata:
      labels:
        run: ftps
    spec:
      containers:
      - name: ftps
        image: service_ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: ftps