apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-share-ip: minikube
  labels:
    run: ftps
spec:
  type: LoadBalancer
  selector:
    run: ftps
  ports:
  - name: ftps
    port: 21
    targetPort: 21
    protocol: TCP
  - name: ftps00
    port: 40000
    protocol: TCP
  - name: ftps01
    port: 20000
    protocol: TCP
  - name: ftps02
    port: 50000
    protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ftps
  labels:
    run: ftps
spec:
  serviceName: ftps
  replicas: 1
  selector:
    matchLabels:
      run: ftps
  template:
    metadata:
      labels:
        run: ftps
    spec:
      containers:
      - name: ftps
        image: service_ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: ftps
        - containerPort: 40000
          name: ftps00
        - containerPort: 20000
          name: ftps01
        - containerPort: 50000
          name: ftps02