apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
  name: ftps-service
  labels:
    run: ftps
spec:
  ports:
    - port: 21
      name: ftps
    - port: 21000
      name: ftps00
    - port: 21001
      name: ftps01
    - port: 21002
      name: ftps02
    - port: 21003
      name: ftps03
  selector:
    run: ftps
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-pv-claim
  labels:
    run: ftps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: ftps
  labels:
    run: ftps
spec:
  serviceName: ftps
  selector:
    matchLabels:
      run: ftps
  replicas: 1
  template:
    metadata:
      labels:
        run: ftps
    spec:
      containers:
      - image: service_ftps
        imagePullPolicy: Never
        name: ftps
        ports:
        - containerPort: 21
          hostPort: 21
        - containerPort: 21000
          hostPort: 21000
        - containerPort: 21001
          hostPort: 21001
        - containerPort: 21002
          hostPort: 21002
        - containerPort: 21003
          hostPort: 21003
        volumeMounts:
        - name: ftps-persistent-storage
          mountPath: /ftps
      volumes:
      - name: ftps-persistent-storage
        persistentVolumeClaim:
          claimName: ftps-pv-claim